### Monogdb service
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    purpose: mini-project
    tier: database
spec:
  selector:
    purpose: mini-project
    tier: database
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017

---
apiVersion: apps/v1
kind: StatefulSet
metadata:   
  name: mongodb
  labels:
    purpose: mini-project
    tier: database
spec:
  selector:
    matchLabels:
      purpose: mini-project
      tier: database
  replicas: 2
  ### This is Pod definition
  template:
    metadata:
      name: mongodb
      labels:
        purpose: mini-project
        tier: database
    spec:
      containers:
      - name: mongodb
        image: mohanvamsi011/mongodb:v1
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
  ### this is pvc definition
  volumeClaimTemplates:
  - metadata:
      name: mongodb-data
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: ebs-miniproject
      resources:
        requests:
          storage: 2Gi


